#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiveSDKSampleAndroid.Resource", IsApplication=true)]

namespace LiveSDKSampleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audio_x_generic = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int folder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int folder_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int image_x_generic = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int text_x_preview = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int video_x_generic = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int beginTextView = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int beginTextViewNeedId = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int cancelButton = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int descriptionEditText = 2131034121;
			
			// aapt resource value: 0x7f05001b
			public const int descriptionTextView = 2131034139;
			
			// aapt resource value: 0x7f050006
			public const int femaleRadio = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int firstNameEditText = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int genderRadioGroup = 2131034116;
			
			// aapt resource value: 0x7f05001e
			public const int genderTextView = 2131034142;
			
			// aapt resource value: 0x7f05000c
			public const int httpMethodSpinner = 2131034124;
			
			// aapt resource value: 0x7f05001c
			public const int idTextView = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int isFavoriteTextView = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int isFriendTextView = 2131034143;
			
			// aapt resource value: 0x7f050003
			public const int lastNameEditText = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout1 = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout2 = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int maleRadio = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int nameEditText = 2131034120;
			
			// aapt resource value: 0x7f050014
			public const int nameTextView = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int needIdButton = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int pathText = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int requestBodyText = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int requestBodyTextView = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int responseBodyText = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int saveButton = 2131034119;
			
			// aapt resource value: 0x7f050019
			public const int signInButton = 2131034137;
			
			// aapt resource value: 0x7f050022
			public const int signOutButton = 2131034146;
			
			// aapt resource value: 0x7f05001a
			public const int skyDriveItemIcon = 2131034138;
			
			// aapt resource value: 0x7f050011
			public const int submitButton = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int textView3 = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int typeTextView = 2131034133;
			
			// aapt resource value: 0x7f050021
			public const int updatedTimeTextView = 2131034145;
			
			// aapt resource value: 0x7f05001d
			public const int userIdTextView = 2131034141;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int create_contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int create_folder = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int explorer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int file_picker = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int file_picker_list_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int signin = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int skydrive = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int skydrive_list_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int view_contact = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int view_contacts = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int view_contacts_list_item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int view_profile = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040019
			public const int AndroidSignInHelpLink = 2130968601;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int begin = 2130968600;
			
			// aapt resource value: 0x7f04000b
			public const int cancel = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int description = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int female = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int first_name = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int http_method_prompt = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int last_name = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int male = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int name = 2130968580;
			
			// aapt resource value: 0x7f040012
			public const int no_contacts = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int no_files = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int no_skydrive_items = 2130968595;
			
			// aapt resource value: 0x7f04000e
			public const int path_hint = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int request_body = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int request_body_hint = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int request_method = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int request_path = 2130968596;
			
			// aapt resource value: 0x7f040001
			public const int response_display = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int save = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int sign_in = 2130968588;
			
			// aapt resource value: 0x7f040016
			public const int sign_out = 2130968598;
			
			// aapt resource value: 0x7f040011
			public const int skydrive_icon_description = 2130968593;
			
			// aapt resource value: 0x7f040002
			public const int submit_display = 2130968578;
			
			// aapt resource value: 0x7f04001b
			public const int unset_client_message_body = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int unset_client_message_negitive = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int unset_client_message_positive = 2130968604;
			
			// aapt resource value: 0x7f04001a
			public const int unset_client_message_title = 2130968602;
			
			// aapt resource value: 0x7f040017
			public const int welcome = 2130968599;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
